### PR TITLE
fix some golangci-lint, revive linter warnings

### PR DESCRIPTION
**Pull request by s3rj1k**
This PR fixes some issues that were reported by golangci and revive linters.

Signed-off-by: s3rj1k <evasive.gyron@gmail.com>

### CODE REVIEW

**Comment by s3rj1k** [comment]
@sqs would be nice for this to be merged so some more work could be done with code

**Comment by sqs** [comment]
Thanks! Could you please remove instead of commenting out code (I saw 2 instances of this)? Then I will approve and merge.

**Comment by sqs** [comment]
I just made those changes and pushed them to your branch. Will merge when CI is green.

**Comment by s3rj1k** [comment]
@sqs super, as a bonus, you did a go.mod. thanks )

**Pull request merged**
